name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test colmap wrapper
        run: |
          from colmap_wrapper.data.download import Dataset
          from colmap_wrapper.visualization import ColmapVisualization
      
          downloader = Dataset()
          downloader.download_bunny_dataset()
      
          project = COLMAPProject(project_path=downloader.file_path,
                                  load_images=True,
                                  load_depth=True,
                                  image_resize=0.4)
      
          camera = project.cameras
          images = project.images
          sparse = project.get_sparse()
          dense = project.get_dense()
